# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-23 06:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('edx_proctoring', '0009_proctoredexamreviewpolicy_remove_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProctoredExamStudentOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('otp', models.CharField(max_length=10, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('expires_at', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=64)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edx_proctoring.ProctoredExam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'proctoring_proctoredexamstudentotp',
                'verbose_name': 'proctored exam student otp',
            },
        ),
        migrations.AlterUniqueTogether(
            name='proctoredexamstudentotp',
            unique_together=set([('exam', 'user', 'otp')]),
        ),
    ]
